name: Create Release
description: Create GitHub release and upload packaged artifacts

runs:
  using: composite
  steps:
    - name: Get version info
      id: version
      shell: bash
      run: |
        helium_version=$(python3 "helium-chromium/utils/helium_version.py" --tree "helium-chromium/" --platform-tree "." --print)
        echo "version=${helium_version}" >> $GITHUB_OUTPUT

    - name: Download AppImage artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: helium-*-AppImage
        path: ./release/
        merge-multiple: true

    - name: Download tar.xz artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: helium-*-linux
        path: ./release/
        merge-multiple: true

    - name: List release files
      shell: bash
      run: ls -la release/

    - name: Create Release
      uses: imputnet/action-gh-release@v2.5
      with:
        tag_name: ${{ steps.version.outputs.version }}
        prerelease: true
        fail_on_unmatched_files: true
        files: |
          release/helium-*.AppImage
          release/helium-*.AppImage.zsync
          release/helium-*_linux.tar.xz
