name: Create Release
description: Create GitHub release and upload packaged artifacts

runs:
  using: composite
  steps:
    - name: Get version info
      id: version
      shell: bash
      run: |
        helium_version=$(python3 "helium-chromium/utils/helium_version.py" --tree "helium-chromium/" --platform-tree "." --print)
        echo "version=${helium_version}" >> $GITHUB_OUTPUT

    - name: Download AppImage artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: helium-*-AppImage
        path: ./release/
        merge-multiple: true

    - name: Download tar.xz artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: helium-*-linux
        path: ./release/
        merge-multiple: true

    - name: Generate AppImage .zsync file for updates
      run: |
        # Install zsync if not already available (common on Ubuntu runners)
        sudo apt-get update
        sudo apt-get install -y zsync

        # Generate .zsync from the downloaded AppImage
        # Assumes your AppImage filename follows the pattern; use the extracted $helium_version var if available
        VERSION="0.5.7.1"  # Replace with ${{ steps.get_version.outputs.version }} or similar from your python step
        zsyncmake -n "Helium $VERSION x86_64" -u "https://github.com/jhelfer/helium-linux/releases/download/v$VERSION/helium-$VERSION-x86_64.AppImage" \
                  -o "release/helium-$VERSION-x86_64.AppImage.zsync" \
                  "release/helium-$VERSION-x86_64.AppImage"
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: List release files
      shell: bash
      run: ls -la release/

    - name: Create Release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1, pinned commit hash
      with:
        tag_name: ${{ steps.version.outputs.version }}
        prerelease: true
        fail_on_unmatched_files: false
        files: |
          release/helium-*.AppImage
          release/helium-*.AppImage.zsync
          release/helium-*_linux.tar.xz
