name: Create Release
description: Create GitHub release and upload packaged artifacts

runs:
  using: composite
  steps:
    - name: Get version info
      id: version
      shell: bash
      run: |
        helium_version=$(python3 "helium-chromium/utils/helium_version.py" --tree "helium-chromium/" --platform-tree "." --print)
        echo "version=${helium_version}" >> $GITHUB_OUTPUT

    - name: Download AppImage artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: helium-*-AppImage
        path: ./release/
        merge-multiple: true

    - name: Download tar.xz artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: helium-*-linux
        path: ./release/
        merge-multiple: true

    - name: List release files
      shell: bash
      run: ls -la release/

    - name: Create release notes
      shell: bash
      run: |
        GH_RUN_HREF="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"

        submodule_commit_at() {
            git ls-tree "$1" helium-chromium | awk '{print $3}'
        }

        LAST_TAG=$(git describe --tags --abbrev=0)
        COMMIT_THEN=$(submodule_commit_at "$LAST_TAG")
        COMMIT_NOW=$(submodule_commit_at HEAD)

        {
          printf 'Changes since last build:\n### helium-linux\n```\n'
          git log --oneline "$LAST_TAG..HEAD"
          printf '```\n\n### helium-chromium\n```\n'
          git -C helium-chromium log --oneline "$COMMIT_THEN..$COMMIT_NOW"
          printf '```\n\n---\n\n'
          printf 'See [this GitHub Actions Run](%s) for the [Workflow file](%s/workflow) used '
          printf 'as well as the build logs and artifacts\n' "$GH_RUN_HREF" "$GH_RUN_HREF" 
        } | tee ./github_release_note.md

    - name: Create Release
      uses: imputnet/action-gh-release@v2.5
      with:
        tag_name: ${{ steps.version.outputs.version }}
        prerelease: true
        fail_on_unmatched_files: true
        body_path: ./github_release_note.md
        files: |
          release/helium-*.AppImage
          release/helium-*.AppImage.zsync
          release/helium-*_linux.tar.xz*
